[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements-deploy.txt"]

[start]
cmd = "python3 main.py serve --port ${PORT:-8000}"
